services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram-bot.py
    envVars:
      - key: 7652627861:AAHhq0HUA-15Ig71m-HY7gMp2zhzRkr4wxg
        sync: false